This is makeindex, version 2.15 [MiKTeX 2.9.6350 64-bit] (kpathsea + Thai support).
Scanning style file ./rapport_stage.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file rapport_stage.acn....done (6 entries accepted, 0 rejected).
Sorting entries....done (20 comparisons).
Generating output file rapport_stage.acr....done (21 lines written, 0 warnings).
Output written in rapport_stage.acr.
Transcript written in rapport_stage.alg.
