This is makeindex, version 2.15 [MiKTeX 2.9.6350 64-bit] (kpathsea + Thai support).
Scanning style file ./rapport_seq8.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file rapport_seq8.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file rapport_seq8.acr....done (6 lines written, 0 warnings).
Output written in rapport_seq8.acr.
Transcript written in rapport_seq8.alg.
